//! Binary entrypoint for `rust_mc_vrp`.

use std::collections::BTreeMap;
use std::fs::File;
use std::io::{self, BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::process::exit;

use clap::{Args, Parser, Subcommand};

mod graph;
mod nsga;

use graph::Graph;
use nsga::{InsertionStrategy, NSGA, NsgaRunResult, RunConfig};

const DEFAULT_GRAPH_PATH: &str = "xset/X-n176-k26.vrp";
const DEFAULT_BENCH_SUITE: [&str; 5] = [
    "xset/X-n101-k25.vrp",
    "xset/X-n120-k6.vrp",
    "xset/X-n176-k26.vrp",
    "xset/X-n223-k34.vrp",
    "xset/X-n280-k17.vrp",
];

#[derive(Parser)]
#[command(author, version, about = "Solve CVRP using NSGA-II")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    Solve(SolveArgs),
    Bench(BenchArgs),
}

#[derive(Args, Clone, Debug)]
struct SolverArgs {
    /// Number of individuals in the population.
    #[arg(short, long, default_value = "100")]
    population_size: u32,

    /// Crossover probability.
    #[arg(long, default_value = "0.2")]
    p_crossover: f64,

    /// Mutation probability.
    #[arg(long, default_value = "0.2")]
    p_mutation: f64,

    /// Percentage of the initial population generated by random shuffling.
    #[arg(long, default_value = "0")]
    init_random_pct: u32,

    /// Percentage of the initial population generated by best insertion.
    #[arg(long, default_value = "100")]
    init_best_insertion_pct: u32,

    /// Best-insertion strategy for constructive initialization.
    #[arg(long, value_enum, default_value = "best-distance")]
    init_insertion_strategy: InsertionStrategy,

    /// Best-insertion strategy for relocate mutation.
    #[arg(long, value_enum, default_value = "best-distance")]
    relocate_insertion_strategy: InsertionStrategy,

    /// Seed for the random secondary objective in the graph.
    #[arg(long, default_value = "1")]
    graph_seed: u64,

    /// Base seed for the evolutionary search.
    #[arg(long, default_value = "1")]
    nsga_seed: u64,

    /// Number of independent runs to execute.
    #[arg(long, default_value = "1")]
    runs: u32,

    /// Maximum number of generations.
    #[arg(long, default_value = "500")]
    max_generations: usize,

    /// Hypervolume stall window.
    #[arg(long, default_value = "30")]
    hv_window: usize,

    /// Hypervolume stall epsilon.
    #[arg(long, default_value = "1e-6")]
    hv_eps: f64,

    /// Emit progress every N generations. Use 0 to silence generation logs.
    #[arg(long, default_value = "0")]
    log_every: usize,

    /// Percentage of mutation picks assigned to intra-route inversion.
    #[arg(long, default_value = "30")]
    mutation_inversion_pct: u32,

    /// Percentage of mutation picks assigned to relocate.
    #[arg(long, default_value = "60")]
    mutation_relocate_pct: u32,

    /// Percentage of mutation picks assigned to swap.
    #[arg(long, default_value = "10")]
    mutation_swap_pct: u32,

    /// Percentage of mutation picks assigned to or-opt segment relocation.
    #[arg(long, default_value = "0")]
    mutation_or_opt_pct: u32,

    /// Percentage of mutation picks assigned to destroy-and-repair.
    #[arg(long, default_value = "0")]
    mutation_destroy_repair_pct: u32,

    /// Number of sampled nodes used in the post-mutation reinsertion polish.
    #[arg(long, default_value = "8")]
    mutation_refine_sample_size: usize,
}

#[derive(Args, Clone, Debug)]
struct SolveArgs {
    /// Path to a TSPLIB-like `.vrp` file (Uchoa X-set style).
    #[arg(short, long, default_value = DEFAULT_GRAPH_PATH)]
    graph_path: String,

    #[command(flatten)]
    solver: SolverArgs,

    /// Only print summary metrics instead of the full Pareto set.
    #[arg(long, default_value_t = false)]
    summary_only: bool,

    /// Write solve output to this file (otherwise stdout).
    #[arg(long)]
    output: Option<PathBuf>,
}

#[derive(Args, Clone, Debug)]
struct BenchArgs {
    /// Instance(s) to benchmark. When omitted, a small+medium default suite is used.
    #[arg(long = "instance")]
    instances: Vec<String>,

    #[command(flatten)]
    solver: SolverArgs,

    /// CSV path for benchmark rows.
    #[arg(long, default_value = "bench_results.csv")]
    csv_output: PathBuf,
}

#[derive(Clone, Debug)]
struct BenchRow {
    instance: String,
    run: u32,
    graph_seed: u64,
    nsga_seed: u64,
    variant: String,
    generations: usize,
    elapsed_ms: u128,
    pareto_size: usize,
    best_pareto_distance: f64,
    best_pareto_secondary: f64,
    benchmark_distance: Option<f64>,
    min_distance_gap_pct: Option<f64>,
    hv_final: f64,
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Command::Solve(args) => {
            if let Err(err) = validate_solver_args(&args.solver) {
                eprintln!("{err}");
                exit(1);
            }

            if let Some(path) = &args.output {
                let file = match File::create(path) {
                    Ok(file) => file,
                    Err(err) => {
                        eprintln!("Failed to create output file '{}': {}", path.display(), err);
                        exit(1);
                    }
                };
                let mut writer = io::BufWriter::new(file);
                if let Err(err) = execute_solve(&args, &mut writer) {
                    eprintln!("{err}");
                    exit(1);
                }
                let _ = writer.flush();
            } else {
                let stdout = io::stdout();
                let mut writer = io::BufWriter::new(stdout.lock());
                if let Err(err) = execute_solve(&args, &mut writer) {
                    eprintln!("{err}");
                    exit(1);
                }
                let _ = writer.flush();
            }
        }
        Command::Bench(args) => {
            if let Err(err) = validate_solver_args(&args.solver) {
                eprintln!("{err}");
                exit(1);
            }

            let csv_file = match File::create(&args.csv_output) {
                Ok(file) => file,
                Err(err) => {
                    eprintln!(
                        "Failed to create benchmark CSV '{}': {}",
                        args.csv_output.display(),
                        err
                    );
                    exit(1);
                }
            };
            let mut csv_writer = io::BufWriter::new(csv_file);
            let stdout = io::stdout();
            let mut summary_writer = io::BufWriter::new(stdout.lock());

            if let Err(err) = execute_bench(&args, &mut csv_writer, &mut summary_writer) {
                eprintln!("{err}");
                exit(1);
            }
            let _ = csv_writer.flush();
            let _ = summary_writer.flush();
        }
    }
}

fn validate_solver_args(args: &SolverArgs) -> Result<(), String> {
    if args.runs == 0 {
        return Err("--runs must be >= 1".to_string());
    }
    if args.init_random_pct > 100 || args.init_best_insertion_pct > 100 {
        return Err("initialization percentages must be in 0..=100".to_string());
    }
    if args.init_random_pct + args.init_best_insertion_pct != 100 {
        return Err("--init-random-pct + --init-best-insertion-pct must equal 100".to_string());
    }
    if args.hv_window < 2 {
        return Err("--hv-window must be >= 2".to_string());
    }
    if !(0.0..=1.0).contains(&args.p_crossover) {
        return Err("--p-crossover must be in 0..=1".to_string());
    }
    if !(0.0..=1.0).contains(&args.p_mutation) {
        return Err("--p-mutation must be in 0..=1".to_string());
    }
    if args.max_generations == 0 {
        return Err("--max-generations must be >= 1".to_string());
    }
    if args.mutation_inversion_pct > 100
        || args.mutation_relocate_pct > 100
        || args.mutation_swap_pct > 100
        || args.mutation_or_opt_pct > 100
        || args.mutation_destroy_repair_pct > 100
    {
        return Err("mutation percentages must be in 0..=100".to_string());
    }
    if args.mutation_inversion_pct
        + args.mutation_relocate_pct
        + args.mutation_swap_pct
        + args.mutation_or_opt_pct
        + args.mutation_destroy_repair_pct
        != 100
    {
        return Err(
            "--mutation-inversion-pct + --mutation-relocate-pct + --mutation-swap-pct + --mutation-or-opt-pct + --mutation-destroy-repair-pct must equal 100"
                .to_string(),
        );
    }
    Ok(())
}

fn execute_solve<W: Write>(args: &SolveArgs, w: &mut W) -> io::Result<()> {
    let graph = Graph::new_with_seed(&args.graph_path, args.solver.graph_seed)?;
    let benchmark_distance = load_benchmark_distance(&args.graph_path)?;

    for run_idx in 0..args.solver.runs {
        let run_number = run_idx + 1;
        let nsga_seed = args.solver.nsga_seed + run_idx as u64;
        writeln!(w, "=== Solve Run {}/{} ===", run_number, args.solver.runs)?;
        writeln!(w, "Graph: {}", args.graph_path)?;
        writeln!(w, "Graph seed: {}", args.solver.graph_seed)?;
        writeln!(w, "NSGA seed: {}", nsga_seed)?;
        writeln!(w, "Population size: {}", args.solver.population_size)?;
        writeln!(
            w,
            "Insertion strategies: init={}, relocate={}",
            args.solver.init_insertion_strategy.as_str(),
            args.solver.relocate_insertion_strategy.as_str()
        )?;
        writeln!(
            w,
            "Mutation config: p_mutation={}, inversion={}, relocate={}, swap={}, or_opt={}, destroy_repair={}, refine_sample_size={}",
            args.solver.p_mutation,
            args.solver.mutation_inversion_pct,
            args.solver.mutation_relocate_pct,
            args.solver.mutation_swap_pct,
            args.solver.mutation_or_opt_pct,
            args.solver.mutation_destroy_repair_pct,
            args.solver.mutation_refine_sample_size
        )?;

        let result = build_nsga(graph.clone(), &args.solver, nsga_seed).solve_with_writer(w);
        write_result_summary(w, &result, benchmark_distance)?;

        if !args.summary_only {
            writeln!(
                w,
                "Full Pareto set (sorted by distance): {} solutions",
                result.pareto_front.len()
            )?;
            for (idx, solution) in result.pareto_front.iter().enumerate() {
                writeln!(
                    w,
                    "  Solution {}: ({:.3}, {:.3})",
                    idx + 1,
                    solution.fitness_values.0,
                    solution.fitness_values.1
                )?;
                for (route_idx, route) in solution.routes.iter().enumerate() {
                    writeln!(w, "    Route {}: {:?}", route_idx + 1, route)?;
                }
            }
        }

        writeln!(w)?;
    }

    Ok(())
}

fn execute_bench<WCsv: Write, WSummary: Write>(
    args: &BenchArgs,
    csv_writer: &mut WCsv,
    summary_writer: &mut WSummary,
) -> io::Result<()> {
    let instances = if args.instances.is_empty() {
        DEFAULT_BENCH_SUITE
            .iter()
            .map(|instance| instance.to_string())
            .collect::<Vec<_>>()
    } else {
        args.instances.clone()
    };

    write_bench_header(csv_writer)?;
    let variant = variant_label(&args.solver);
    let mut rows = Vec::new();

    for instance in instances {
        let graph = Graph::new_with_seed(&instance, args.solver.graph_seed)?;
        let benchmark_distance = load_benchmark_distance(&instance)?;

        for run_idx in 0..args.solver.runs {
            let nsga_seed = args.solver.nsga_seed + run_idx as u64;
            let mut sink = io::sink();
            let result = build_nsga(graph.clone(), &args.solver, nsga_seed).solve_with_writer(&mut sink);
            let best = result
                .pareto_front
                .first()
                .map(|solution| solution.fitness_values)
                .unwrap_or((f64::INFINITY, f64::INFINITY));

            let row = BenchRow {
                instance: instance.clone(),
                run: run_idx + 1,
                graph_seed: args.solver.graph_seed,
                nsga_seed,
                variant: variant.clone(),
                generations: result.generations,
                elapsed_ms: result.elapsed_ms,
                pareto_size: result.pareto_front.len(),
                best_pareto_distance: best.0,
                best_pareto_secondary: best.1,
                benchmark_distance,
                min_distance_gap_pct: benchmark_distance.map(|benchmark| {
                    min_distance_gap_pct(best.0, benchmark)
                }),
                hv_final: result.hv_final,
            };
            write_bench_row(csv_writer, &row)?;
            rows.push(row);
        }
    }

    write_bench_summary(summary_writer, &rows)?;
    Ok(())
}

fn build_nsga(graph: Graph, args: &SolverArgs, nsga_seed: u64) -> NSGA {
    NSGA::new(
        graph,
        args.population_size,
        args.p_crossover,
        args.p_mutation,
        args.init_random_pct,
        args.init_best_insertion_pct,
        args.init_insertion_strategy,
        args.relocate_insertion_strategy,
        args.mutation_inversion_pct,
        args.mutation_relocate_pct,
        args.mutation_swap_pct,
        args.mutation_or_opt_pct,
        args.mutation_destroy_repair_pct,
        args.mutation_refine_sample_size,
        nsga_seed,
        RunConfig {
            max_generations: args.max_generations,
            hv_window: args.hv_window,
            hv_eps: args.hv_eps,
            log_every: args.log_every,
        },
    )
}

fn write_result_summary<W: Write>(
    w: &mut W,
    result: &NsgaRunResult,
    benchmark_distance: Option<f64>,
) -> io::Result<()> {
    writeln!(w, "Generations: {}", result.generations)?;
    writeln!(w, "Elapsed ms: {}", result.elapsed_ms)?;
    writeln!(w, "Pareto set size: {}", result.pareto_front.len())?;
    writeln!(w, "Archive size: {}", result.archive_size)?;
    writeln!(w, "Final HV: {:.6}", result.hv_final)?;
    writeln!(w, "Converged: {}", result.converged)?;

    if let Some(best) = result.pareto_front.first() {
        writeln!(
            w,
            "Best Pareto distance solution: ({:.3}, {:.3})",
            best.fitness_values.0,
            best.fitness_values.1
        )?;
        if let Some(benchmark) = benchmark_distance {
            writeln!(w, "Benchmark distance: {:.3}", benchmark)?;
            writeln!(
                w,
                "Min-distance gap pct: {:.6}",
                min_distance_gap_pct(best.fitness_values.0, benchmark)
            )?;
        }
    }

    Ok(())
}

fn write_bench_header<W: Write>(w: &mut W) -> io::Result<()> {
    writeln!(
        w,
        "instance,run,graph_seed,nsga_seed,variant,generations,elapsed_ms,pareto_size,best_pareto_distance,best_pareto_secondary,benchmark_distance,min_distance_gap_pct,hv_final"
    )
}

fn write_bench_row<W: Write>(w: &mut W, row: &BenchRow) -> io::Result<()> {
    writeln!(
        w,
        "{},{},{},{},{},{},{},{},{:.6},{:.6},{},{},{:.6}",
        row.instance,
        row.run,
        row.graph_seed,
        row.nsga_seed,
        row.variant,
        row.generations,
        row.elapsed_ms,
        row.pareto_size,
        row.best_pareto_distance,
        row.best_pareto_secondary,
        format_optional_float(row.benchmark_distance),
        format_optional_float(row.min_distance_gap_pct),
        row.hv_final
    )
}

fn write_bench_summary<W: Write>(w: &mut W, rows: &[BenchRow]) -> io::Result<()> {
    let mut grouped: BTreeMap<&str, Vec<&BenchRow>> = BTreeMap::new();
    for row in rows {
        grouped.entry(&row.variant).or_default().push(row);
    }

    for (variant, variant_rows) in grouped {
        let mut gaps: Vec<f64> = variant_rows
            .iter()
            .filter_map(|row| row.min_distance_gap_pct)
            .collect();
        gaps.sort_by(|a, b| a.total_cmp(b));
        let avg_gap = if gaps.is_empty() {
            None
        } else {
            Some(gaps.iter().sum::<f64>() / gaps.len() as f64)
        };
        let median_gap = median(&gaps);

        writeln!(w, "Variant: {}", variant)?;
        writeln!(w, "  Rows: {}", variant_rows.len())?;
        if let Some(avg_gap) = avg_gap {
            writeln!(w, "  Average min-distance gap pct: {:.6}", avg_gap)?;
        } else {
            writeln!(w, "  Average min-distance gap pct: n/a")?;
        }
        if let Some(median_gap) = median_gap {
            writeln!(w, "  Median min-distance gap pct: {:.6}", median_gap)?;
        } else {
            writeln!(w, "  Median min-distance gap pct: n/a")?;
        }
        if let Some(best_row) = variant_rows.iter().min_by(|a, b| {
            a.best_pareto_distance
                .total_cmp(&b.best_pareto_distance)
                .then_with(|| a.best_pareto_secondary.total_cmp(&b.best_pareto_secondary))
        }) {
            writeln!(
                w,
                "  Best row: instance={}, run={}, best_pareto_distance={:.6}",
                best_row.instance,
                best_row.run,
                best_row.best_pareto_distance
            )?;
        }
        writeln!(w)?;
    }

    Ok(())
}

fn variant_label(args: &SolverArgs) -> String {
    format!(
        "pop{}_pc{:.2}_pm{:.2}_init{}_rel{}_rand{}_best{}",
        args.population_size,
        args.p_crossover,
        args.p_mutation,
        args.init_insertion_strategy.as_str(),
        args.relocate_insertion_strategy.as_str(),
        args.init_random_pct,
        args.init_best_insertion_pct
    ) + &format!(
        "_mut{}-{}-{}_rs{}",
        args.mutation_inversion_pct,
        args.mutation_relocate_pct,
        args.mutation_swap_pct,
        args.mutation_refine_sample_size
    ) + &format!(
        "_oo{}_dr{}",
        args.mutation_or_opt_pct,
        args.mutation_destroy_repair_pct
    )
}

fn benchmark_solution_path(instance_path: &str) -> PathBuf {
    Path::new(instance_path).with_extension("sol")
}

fn load_benchmark_distance(instance_path: &str) -> io::Result<Option<f64>> {
    parse_benchmark_cost(&benchmark_solution_path(instance_path))
}

fn parse_benchmark_cost(path: &Path) -> io::Result<Option<f64>> {
    if !path.exists() {
        return Ok(None);
    }

    let file = File::open(path)?;
    let reader = BufReader::new(file);
    for line in reader.lines() {
        let line = line?;
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("Cost") {
            let value = rest.trim().parse::<f64>().map_err(|err| {
                io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("Failed to parse benchmark cost in '{}': {}", path.display(), err),
                )
            })?;
            return Ok(Some(value));
        }
    }

    Ok(None)
}

fn min_distance_gap_pct(best_distance: f64, benchmark_distance: f64) -> f64 {
    100.0 * (best_distance - benchmark_distance) / benchmark_distance
}

fn median(values: &[f64]) -> Option<f64> {
    if values.is_empty() {
        return None;
    }
    let mid = values.len() / 2;
    if values.len() % 2 == 1 {
        Some(values[mid])
    } else {
        Some((values[mid - 1] + values[mid]) / 2.0)
    }
}

fn format_optional_float(value: Option<f64>) -> String {
    value
        .map(|value| format!("{:.6}", value))
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::{
        execute_bench, execute_solve, min_distance_gap_pct, parse_benchmark_cost, BenchArgs,
        SolveArgs, SolverArgs,
    };
    use std::path::Path;

    fn test_solver_args() -> SolverArgs {
        SolverArgs {
            population_size: 12,
            p_crossover: 0.5,
            p_mutation: 0.1,
            init_random_pct: 0,
            init_best_insertion_pct: 100,
            init_insertion_strategy: crate::nsga::InsertionStrategy::BestWeighted,
            relocate_insertion_strategy: crate::nsga::InsertionStrategy::BestWeighted,
            graph_seed: 1,
            nsga_seed: 1,
            runs: 2,
            max_generations: 5,
            hv_window: 3,
            hv_eps: 1e-6,
            log_every: 0,
            mutation_inversion_pct: 55,
            mutation_relocate_pct: 30,
            mutation_swap_pct: 15,
            mutation_or_opt_pct: 0,
            mutation_destroy_repair_pct: 0,
            mutation_refine_sample_size: 8,
        }
    }

    #[test]
    fn benchmark_cost_parser_reads_xset_solution() {
        let cost = parse_benchmark_cost(Path::new("xset/X-n101-k25.sol"))
            .unwrap()
            .unwrap();
        assert_eq!(cost, 27591.0);
    }

    #[test]
    fn gap_metric_matches_definition() {
        let gap = min_distance_gap_pct(110.0, 100.0);
        assert!((gap - 10.0).abs() < 1e-9);
    }

    #[test]
    fn solve_smoke_test_emits_summary() {
        let args = SolveArgs {
            graph_path: "xset/X-n101-k25.vrp".to_string(),
            solver: SolverArgs {
                runs: 1,
                ..test_solver_args()
            },
            summary_only: true,
            output: None,
        };

        let mut output = Vec::new();
        execute_solve(&args, &mut output).unwrap();
        let text = String::from_utf8(output).unwrap();

        assert!(text.contains("Pareto set size:"));
        assert!(text.contains("Best Pareto distance solution:"));
    }

    #[test]
    fn bench_smoke_test_emits_stable_csv_shape() {
        let args = BenchArgs {
            instances: vec![
                "xset/X-n101-k25.vrp".to_string(),
                "xset/X-n120-k6.vrp".to_string(),
            ],
            solver: test_solver_args(),
            csv_output: "ignored.csv".into(),
        };

        let mut csv = Vec::new();
        let mut summary = Vec::new();
        execute_bench(&args, &mut csv, &mut summary).unwrap();

        let csv_text = String::from_utf8(csv).unwrap();
        let summary_text = String::from_utf8(summary).unwrap();

        assert_eq!(csv_text.lines().count(), 1 + 4);
        assert!(summary_text.contains("Average min-distance gap pct"));
        assert!(summary_text.contains("Variant:"));
    }
}
